name: Test

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Dump workflow_run event payload
      env:
        WORKFLOW_RUN_PAYLOAD: ${{ toJSON(github.event.workflow_run) }}
      run: echo "$WORKFLOW_RUN_PAYLOAD"

    - name: Setup Node
      uses: actions/setup-node@v2.4.1
      with:
        cache: 'yarn'
        node-version: '14'

    - name: Install dependencies
      run: yarn install --frozen-lockfile --no-progress --non-interactive

    - name: Run build
      run: yarn build

    - name: Run test
      run: yarn test

    - name: Install GitHub API client for GitHub Actions
      run: npm install --prefix .github/actions/create-commit-status

    - name: Create commit status for test workflow on pull request
      run: node .github/actions/create-commit-status
      env:
        CONTEXT: "Test / test (workflow_run)"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHA: ${{ github.event.workflow_run.head_sha }}
        # TODO: Should be conditional based on `yarn test` result
        STATE: "success"
        TARGET_URL: "https://github.com/lukehedger/actions-workflow-run/actions/runs/${{ github.run_id }}"
