name: Test

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # Should be conditional based on PR or manual/main trigger `github.event.workflow_run.event == pull_request
        ref: github.event.workflow_run.head_branch

    - name: Dump workflow_run event payload
      env:
        WORKFLOW_RUN_PAYLOAD: ${{ toJSON(github.event.workflow_run) }}
      run: echo "$WORKFLOW_RUN_PAYLOAD"

    - name: Setup Node
      uses: actions/setup-node@v2.4.1
      with:
        cache: 'yarn'
        node-version: '14'

    - name: Install dependencies
      run: yarn install --frozen-lockfile --no-progress --non-interactive

    - name: Run build
      run: yarn build

    - name: Run test
      run: yarn test
